### ISSUE TITLE
貌似用不了

### ISSUE THREAD

**Issue by wxlbj** [neo5779777/zentao-wecome#1]
hub.zentao.net/app/zentao:20.4 进行的容器化部署进行的测试，管理台安装，直接复制目录，怎么试都没什么用， 没出现项目中企业微信登录相关的东西

**Comment by neo5779777** [comment]
使用最新版20.6容器，进入后台本地安装插件后是正常的
*docker-compose.yaml*
```
version: '2'

networks:
  zentao-net:
    driver: bridge

services:
# mysql service for zentao
  zentao-mysql:
    image: mysql:5.7
    container_name: zentao-mysql
    ports:
      - '13306:3306'
    volumes:
      - /data/zentao/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass4Zentao
      - MYSQL_DATABASE=zentao
    networks:
      - zentao-net

# zentao service
  zentao:
    image: easysoft/zentao:20.6
    container_name: zentao
    ports:
      - '18080:80'
    volumes:
      - /data/zentao/file:/data
    depends_on:
      - zentao-mysql
    environment:
      - ZT_MYSQL_HOST=zentao-mysql
      - ZT_MYSQL_PORT=3306
      - ZT_MYSQL_USER=root
      - ZT_MYSQL_PASSWORD=pass4Zentao
      - ZT_MYSQL_DB=zentao
      - PHP_MAX_EXECUTION_TIME=120
      - PHP_MAX_INPUT_VARS=2000
      - PHP_MEMORY_LIMIT=512M
      - PHP_POST_MAX_SIZE=128M
      - PHP_UPLOAD_MAX_FILESIZE=128M
      - LDAP_ENABLED=false
      - SMTP_ENABLED=false
      - APP_DEFAULT_PORT=80
      - APP_DOMAIN=10.10.20.3
      - PROTOCOL_TYPE=http
      - IS_CONTAINER=true
      - LINK_GIT=false
      - LINK_CI=false
    networks:
      - zentao-net
```


![image](https://github.com/user-attachments/assets/001e85dd-4245-4203-8aad-abd03926dde5)

![image](https://github.com/user-attachments/assets/178f2b1b-efb6-4bf7-a609-d8b258756a0d)
